Cherry pick of 6401948d2002123faa9286160d8f0141a4ccb37f failed
stdout:
CONFLICT (file location): content/applications/finance/accounting/bank/feeds/bank_statements/bank-overview.png added in HEAD inside a directory that was renamed in 6401948d2 ([MOV] accounting: structure of bank sync docs), suggesting it should perhaps be moved to content/applications/finance/accounting/bank/bank_statements/bank-overview.png.
CONFLICT (rename/delete): content/applications/finance/accounting/bank/feeds/bank_statements/bank-statements-01.png renamed to content/applications/finance/accounting/bank/bank_statements/bank-statements-01.png in 6401948d2 ([MOV] accounting: structure of bank sync docs), but deleted in HEAD.
CONFLICT (rename/delete): content/applications/finance/accounting/bank/feeds/bank_statements/bank-statements-02.png renamed to content/applications/finance/accounting/bank/bank_statements/bank-statements-02.png in 6401948d2 ([MOV] accounting: structure of bank sync docs), but deleted in HEAD.
CONFLICT (file location): content/applications/finance/accounting/bank/feeds/bank_statements/import-bank-statement.png added in HEAD inside a directory that was renamed in 6401948d2 ([MOV] accounting: structure of bank sync docs), suggesting it should perhaps be moved to content/applications/finance/accounting/bank/bank_statements/import-bank-statement.png.
Auto-merging content/applications/finance/accounting/bank/setup/bank_accounts.rst
CONFLICT (content): Merge conflict in content/applications/finance/accounting/bank/setup/bank_accounts.rst

stderr:
18:11:56.579030 git.c:455               trace: built-in: git cherry-pick 6401948d2002123faa9286160d8f0141a4ccb37f
error: could not apply 6401948d2... [MOV] accounting: structure of bank sync docs
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: